import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function AudienceModel(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/LiveHouse/Audience.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    Object.values(actions).forEach((action) => {
      if (action) {
        action.play()
      }
    })
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="C3_Idle" position={[1.594, 0, 0.848]}>
          <group name="Skeleton" position={[0, 0, -0.247]}>
            <skinnedMesh
              name="Accessories"
              geometry={nodes.Accessories.geometry}
              material={materials.Color}
              skeleton={nodes.Accessories.skeleton}
            />
            <skinnedMesh
              name="Body"
              geometry={nodes.Body.geometry}
              material={materials.Color}
              skeleton={nodes.Body.skeleton}
            />
            <skinnedMesh
              name="Faces"
              geometry={nodes.Faces.geometry}
              material={materials.Color}
              skeleton={nodes.Faces.skeleton}
            />
            <skinnedMesh
              name="Full_body"
              geometry={nodes.Full_body.geometry}
              material={materials.Color}
              skeleton={nodes.Full_body.skeleton}
            />
            <skinnedMesh
              name="Glasses"
              geometry={nodes.Glasses.geometry}
              material={materials.Color}
              skeleton={nodes.Glasses.skeleton}
            />
            <skinnedMesh
              name="Gloves"
              geometry={nodes.Gloves.geometry}
              material={materials.Color}
              skeleton={nodes.Gloves.skeleton}
            />
            <skinnedMesh
              name="Hairstyle"
              geometry={nodes.Hairstyle.geometry}
              material={materials.Color}
              skeleton={nodes.Hairstyle.skeleton}
            />
            <skinnedMesh
              name="Hat"
              geometry={nodes.Hat.geometry}
              material={materials.Color}
              skeleton={nodes.Hat.skeleton}
            />
            <skinnedMesh
              name="Mustache"
              geometry={nodes.Mustache.geometry}
              material={materials.Color}
              skeleton={nodes.Mustache.skeleton}
            />
            <skinnedMesh
              name="Outerwear"
              geometry={nodes.Outerwear.geometry}
              material={materials.Color}
              skeleton={nodes.Outerwear.skeleton}
            />
            <skinnedMesh
              name="Pants"
              geometry={nodes.Pants.geometry}
              material={materials.Color}
              skeleton={nodes.Pants.skeleton}
            />
            <skinnedMesh
              name="Shoes"
              geometry={nodes.Shoes.geometry}
              material={materials.Color}
              skeleton={nodes.Shoes.skeleton}
            />
            <skinnedMesh
              name="T_Shirt"
              geometry={nodes.T_Shirt.geometry}
              material={materials.Color}
              skeleton={nodes.T_Shirt.skeleton}
            />
            <primitive object={nodes.Root} />
          </group>
        </group>
        <group name="C2_Idle" position={[0.199, 0.03, 0]}>
          <group name="Skeleton001" position={[0, 0, 0.361]}>
            <skinnedMesh
              name="Accessories001"
              geometry={nodes.Accessories001.geometry}
              material={materials['Color.001']}
              skeleton={nodes.Accessories001.skeleton}
            />
            <skinnedMesh
              name="Body001"
              geometry={nodes.Body001.geometry}
              material={materials['Color.001']}
              skeleton={nodes.Body001.skeleton}
            />
            <skinnedMesh
              name="Faces001"
              geometry={nodes.Faces001.geometry}
              material={materials['Color.001']}
              skeleton={nodes.Faces001.skeleton}
            />
            <skinnedMesh
              name="Full_body001"
              geometry={nodes.Full_body001.geometry}
              material={materials['Color.001']}
              skeleton={nodes.Full_body001.skeleton}
            />
            <skinnedMesh
              name="Glasses001"
              geometry={nodes.Glasses001.geometry}
              material={materials['Color.001']}
              skeleton={nodes.Glasses001.skeleton}
            />
            <skinnedMesh
              name="Gloves001"
              geometry={nodes.Gloves001.geometry}
              material={materials['Color.001']}
              skeleton={nodes.Gloves001.skeleton}
            />
            <skinnedMesh
              name="Hairstyle001"
              geometry={nodes.Hairstyle001.geometry}
              material={materials['Color.001']}
              skeleton={nodes.Hairstyle001.skeleton}
            />
            <skinnedMesh
              name="Hat001"
              geometry={nodes.Hat001.geometry}
              material={materials['Color.001']}
              skeleton={nodes.Hat001.skeleton}
            />
            <skinnedMesh
              name="Mustache001"
              geometry={nodes.Mustache001.geometry}
              material={materials['Color.001']}
              skeleton={nodes.Mustache001.skeleton}
            />
            <skinnedMesh
              name="Outerwear001"
              geometry={nodes.Outerwear001.geometry}
              material={materials['Color.001']}
              skeleton={nodes.Outerwear001.skeleton}
            />
            <skinnedMesh
              name="Pants001"
              geometry={nodes.Pants001.geometry}
              material={materials['Color.001']}
              skeleton={nodes.Pants001.skeleton}
            />
            <skinnedMesh
              name="Shoes001"
              geometry={nodes.Shoes001.geometry}
              material={materials['Color.001']}
              skeleton={nodes.Shoes001.skeleton}
            />
            <skinnedMesh
              name="T_Shirt001"
              geometry={nodes.T_Shirt001.geometry}
              material={materials['Color.001']}
              skeleton={nodes.T_Shirt001.skeleton}
            />
            <primitive object={nodes.Root_1} />
          </group>
        </group>
        <group name="C1_Idle" position={[-2.363, 0, 0]}>
          <group name="Skeleton002" position={[5.819, 0, 0.1]}>
            <skinnedMesh
              name="Accessories002"
              geometry={nodes.Accessories002.geometry}
              material={materials['Color.002']}
              skeleton={nodes.Accessories002.skeleton}
            />
            <skinnedMesh
              name="Body002"
              geometry={nodes.Body002.geometry}
              material={materials['Color.002']}
              skeleton={nodes.Body002.skeleton}
            />
            <skinnedMesh
              name="Faces002"
              geometry={nodes.Faces002.geometry}
              material={materials['Color.002']}
              skeleton={nodes.Faces002.skeleton}
            />
            <skinnedMesh
              name="Full_body002"
              geometry={nodes.Full_body002.geometry}
              material={materials['Color.002']}
              skeleton={nodes.Full_body002.skeleton}
            />
            <skinnedMesh
              name="Glasses002"
              geometry={nodes.Glasses002.geometry}
              material={materials['Color.002']}
              skeleton={nodes.Glasses002.skeleton}
            />
            <skinnedMesh
              name="Gloves002"
              geometry={nodes.Gloves002.geometry}
              material={materials['Color.002']}
              skeleton={nodes.Gloves002.skeleton}
            />
            <skinnedMesh
              name="Hairstyle002"
              geometry={nodes.Hairstyle002.geometry}
              material={materials['Color.002']}
              skeleton={nodes.Hairstyle002.skeleton}
            />
            <skinnedMesh
              name="Hat002"
              geometry={nodes.Hat002.geometry}
              material={materials['Color.002']}
              skeleton={nodes.Hat002.skeleton}
            />
            <skinnedMesh
              name="Mustache002"
              geometry={nodes.Mustache002.geometry}
              material={materials['Color.002']}
              skeleton={nodes.Mustache002.skeleton}
            />
            <skinnedMesh
              name="Outerwear002"
              geometry={nodes.Outerwear002.geometry}
              material={materials['Color.002']}
              skeleton={nodes.Outerwear002.skeleton}
            />
            <skinnedMesh
              name="Pants002"
              geometry={nodes.Pants002.geometry}
              material={materials['Color.002']}
              skeleton={nodes.Pants002.skeleton}
            />
            <skinnedMesh
              name="Shoes002"
              geometry={nodes.Shoes002.geometry}
              material={materials['Color.002']}
              skeleton={nodes.Shoes002.skeleton}
            />
            <skinnedMesh
              name="T_Shirt002"
              geometry={nodes.T_Shirt002.geometry}
              material={materials['Color.002']}
              skeleton={nodes.T_Shirt002.skeleton}
            />
            <primitive object={nodes.Root_2} />
          </group>
        </group>
        <group name="C4_Idle" position={[1.421, 0, -1.198]}>
          <group name="Skeleton003" position={[1.297, 0, 0]}>
            <skinnedMesh
              name="Accessories003"
              geometry={nodes.Accessories003.geometry}
              material={materials['Color.003']}
              skeleton={nodes.Accessories003.skeleton}
            />
            <skinnedMesh
              name="Body003"
              geometry={nodes.Body003.geometry}
              material={materials['Color.003']}
              skeleton={nodes.Body003.skeleton}
            />
            <skinnedMesh
              name="Faces003"
              geometry={nodes.Faces003.geometry}
              material={materials['Color.003']}
              skeleton={nodes.Faces003.skeleton}
            />
            <skinnedMesh
              name="Full_body003"
              geometry={nodes.Full_body003.geometry}
              material={materials['Color.003']}
              skeleton={nodes.Full_body003.skeleton}
            />
            <skinnedMesh
              name="Glasses003"
              geometry={nodes.Glasses003.geometry}
              material={materials['Color.003']}
              skeleton={nodes.Glasses003.skeleton}
            />
            <skinnedMesh
              name="Gloves003"
              geometry={nodes.Gloves003.geometry}
              material={materials['Color.003']}
              skeleton={nodes.Gloves003.skeleton}
            />
            <skinnedMesh
              name="Hairstyle003"
              geometry={nodes.Hairstyle003.geometry}
              material={materials['Color.003']}
              skeleton={nodes.Hairstyle003.skeleton}
            />
            <skinnedMesh
              name="Hat003"
              geometry={nodes.Hat003.geometry}
              material={materials['Color.003']}
              skeleton={nodes.Hat003.skeleton}
            />
            <skinnedMesh
              name="Mustache003"
              geometry={nodes.Mustache003.geometry}
              material={materials['Color.003']}
              skeleton={nodes.Mustache003.skeleton}
            />
            <skinnedMesh
              name="Outerwear003"
              geometry={nodes.Outerwear003.geometry}
              material={materials['Color.003']}
              skeleton={nodes.Outerwear003.skeleton}
            />
            <skinnedMesh
              name="Pants003"
              geometry={nodes.Pants003.geometry}
              material={materials['Color.003']}
              skeleton={nodes.Pants003.skeleton}
            />
            <skinnedMesh
              name="Shoes003"
              geometry={nodes.Shoes003.geometry}
              material={materials['Color.003']}
              skeleton={nodes.Shoes003.skeleton}
            />
            <skinnedMesh
              name="T_Shirt003"
              geometry={nodes.T_Shirt003.geometry}
              material={materials['Color.003']}
              skeleton={nodes.T_Shirt003.skeleton}
            />
            <primitive object={nodes.Root_3} />
          </group>
        </group>
        <group name="C5_Idle" position={[4.441, 0, 0.387]}>
          <group name="Skeleton004" position={[-5.916, 0, 0]}>
            <skinnedMesh
              name="Accessories004"
              geometry={nodes.Accessories004.geometry}
              material={materials['Color.004']}
              skeleton={nodes.Accessories004.skeleton}
            />
            <skinnedMesh
              name="Body004"
              geometry={nodes.Body004.geometry}
              material={materials['Color.004']}
              skeleton={nodes.Body004.skeleton}
            />
            <skinnedMesh
              name="Faces004"
              geometry={nodes.Faces004.geometry}
              material={materials['Color.004']}
              skeleton={nodes.Faces004.skeleton}
            />
            <skinnedMesh
              name="Full_body004"
              geometry={nodes.Full_body004.geometry}
              material={materials['Color.004']}
              skeleton={nodes.Full_body004.skeleton}
            />
            <skinnedMesh
              name="Glasses004"
              geometry={nodes.Glasses004.geometry}
              material={materials['Color.004']}
              skeleton={nodes.Glasses004.skeleton}
            />
            <skinnedMesh
              name="Gloves004"
              geometry={nodes.Gloves004.geometry}
              material={materials['Color.004']}
              skeleton={nodes.Gloves004.skeleton}
            />
            <skinnedMesh
              name="Hairstyle004"
              geometry={nodes.Hairstyle004.geometry}
              material={materials['Color.004']}
              skeleton={nodes.Hairstyle004.skeleton}
            />
            <skinnedMesh
              name="Hat004"
              geometry={nodes.Hat004.geometry}
              material={materials['Color.004']}
              skeleton={nodes.Hat004.skeleton}
            />
            <skinnedMesh
              name="Mustache004"
              geometry={nodes.Mustache004.geometry}
              material={materials['Color.004']}
              skeleton={nodes.Mustache004.skeleton}
            />
            <skinnedMesh
              name="Outerwear004"
              geometry={nodes.Outerwear004.geometry}
              material={materials['Color.004']}
              skeleton={nodes.Outerwear004.skeleton}
            />
            <skinnedMesh
              name="Pants004"
              geometry={nodes.Pants004.geometry}
              material={materials['Color.004']}
              skeleton={nodes.Pants004.skeleton}
            />
            <skinnedMesh
              name="Shoes004"
              geometry={nodes.Shoes004.geometry}
              material={materials['Color.004']}
              skeleton={nodes.Shoes004.skeleton}
            />
            <skinnedMesh
              name="T_Shirt004"
              geometry={nodes.T_Shirt004.geometry}
              material={materials['Color.004']}
              skeleton={nodes.T_Shirt004.skeleton}
            />
            <primitive object={nodes.Root_4} />
          </group>
        </group>
        <group name="C7_Idle" position={[-0.757, 0, -0.526]}>
          <group name="Skeleton006" position={[0, 0, 0.481]}>
            <skinnedMesh
              name="Accessories006"
              geometry={nodes.Accessories006.geometry}
              material={materials['Color.006']}
              skeleton={nodes.Accessories006.skeleton}
            />
            <skinnedMesh
              name="Body006"
              geometry={nodes.Body006.geometry}
              material={materials['Color.006']}
              skeleton={nodes.Body006.skeleton}
            />
            <skinnedMesh
              name="Faces006"
              geometry={nodes.Faces006.geometry}
              material={materials['Color.006']}
              skeleton={nodes.Faces006.skeleton}
            />
            <skinnedMesh
              name="Full_body006"
              geometry={nodes.Full_body006.geometry}
              material={materials['Color.006']}
              skeleton={nodes.Full_body006.skeleton}
            />
            <skinnedMesh
              name="Glasses006"
              geometry={nodes.Glasses006.geometry}
              material={materials['Color.006']}
              skeleton={nodes.Glasses006.skeleton}
            />
            <skinnedMesh
              name="Gloves006"
              geometry={nodes.Gloves006.geometry}
              material={materials['Color.006']}
              skeleton={nodes.Gloves006.skeleton}
            />
            <skinnedMesh
              name="Hairstyle006"
              geometry={nodes.Hairstyle006.geometry}
              material={materials['Color.006']}
              skeleton={nodes.Hairstyle006.skeleton}
            />
            <skinnedMesh
              name="Hat006"
              geometry={nodes.Hat006.geometry}
              material={materials['Color.006']}
              skeleton={nodes.Hat006.skeleton}
            />
            <skinnedMesh
              name="Mustache006"
              geometry={nodes.Mustache006.geometry}
              material={materials['Color.006']}
              skeleton={nodes.Mustache006.skeleton}
            />
            <skinnedMesh
              name="Outerwear006"
              geometry={nodes.Outerwear006.geometry}
              material={materials['Color.006']}
              skeleton={nodes.Outerwear006.skeleton}
            />
            <skinnedMesh
              name="Pants006"
              geometry={nodes.Pants006.geometry}
              material={materials['Color.006']}
              skeleton={nodes.Pants006.skeleton}
            />
            <skinnedMesh
              name="Shoes006"
              geometry={nodes.Shoes006.geometry}
              material={materials['Color.006']}
              skeleton={nodes.Shoes006.skeleton}
            />
            <skinnedMesh
              name="T_Shirt006"
              geometry={nodes.T_Shirt006.geometry}
              material={materials['Color.006']}
              skeleton={nodes.T_Shirt006.skeleton}
            />
            <primitive object={nodes.Root_5} />
          </group>
        </group>
        <group name="C8_Idle" position={[-2.123, 0, -0.506]}>
          <group name="Skeleton007" position={[0, 0, 0.481]}>
            <skinnedMesh
              name="Accessories007"
              geometry={nodes.Accessories007.geometry}
              material={materials['Color.007']}
              skeleton={nodes.Accessories007.skeleton}
            />
            <skinnedMesh
              name="Body007"
              geometry={nodes.Body007.geometry}
              material={materials['Color.007']}
              skeleton={nodes.Body007.skeleton}
            />
            <skinnedMesh
              name="Faces007"
              geometry={nodes.Faces007.geometry}
              material={materials['Color.007']}
              skeleton={nodes.Faces007.skeleton}
            />
            <skinnedMesh
              name="Full_body007"
              geometry={nodes.Full_body007.geometry}
              material={materials['Color.007']}
              skeleton={nodes.Full_body007.skeleton}
            />
            <skinnedMesh
              name="Glasses007"
              geometry={nodes.Glasses007.geometry}
              material={materials['Color.007']}
              skeleton={nodes.Glasses007.skeleton}
            />
            <skinnedMesh
              name="Gloves007"
              geometry={nodes.Gloves007.geometry}
              material={materials['Color.007']}
              skeleton={nodes.Gloves007.skeleton}
            />
            <skinnedMesh
              name="Hairstyle007"
              geometry={nodes.Hairstyle007.geometry}
              material={materials['Color.007']}
              skeleton={nodes.Hairstyle007.skeleton}
            />
            <skinnedMesh
              name="Hat007"
              geometry={nodes.Hat007.geometry}
              material={materials['Color.007']}
              skeleton={nodes.Hat007.skeleton}
            />
            <skinnedMesh
              name="Mustache007"
              geometry={nodes.Mustache007.geometry}
              material={materials['Color.007']}
              skeleton={nodes.Mustache007.skeleton}
            />
            <skinnedMesh
              name="Outerwear007"
              geometry={nodes.Outerwear007.geometry}
              material={materials['Color.007']}
              skeleton={nodes.Outerwear007.skeleton}
            />
            <skinnedMesh
              name="Pants007"
              geometry={nodes.Pants007.geometry}
              material={materials['Color.007']}
              skeleton={nodes.Pants007.skeleton}
            />
            <skinnedMesh
              name="Shoes007"
              geometry={nodes.Shoes007.geometry}
              material={materials['Color.007']}
              skeleton={nodes.Shoes007.skeleton}
            />
            <skinnedMesh
              name="T_Shirt007"
              geometry={nodes.T_Shirt007.geometry}
              material={materials['Color.007']}
              skeleton={nodes.T_Shirt007.skeleton}
            />
            <primitive object={nodes.Root_6} />
          </group>
        </group>
        <group name="C9_Idle" position={[-2.951, 0, 0.155]}>
          <group name="Skeleton008" position={[0, 0, 0.235]}>
            <skinnedMesh
              name="Accessories008"
              geometry={nodes.Accessories008.geometry}
              material={materials['Color.008']}
              skeleton={nodes.Accessories008.skeleton}
            />
            <skinnedMesh
              name="Body008"
              geometry={nodes.Body008.geometry}
              material={materials['Color.008']}
              skeleton={nodes.Body008.skeleton}
            />
            <skinnedMesh
              name="Faces008"
              geometry={nodes.Faces008.geometry}
              material={materials['Color.008']}
              skeleton={nodes.Faces008.skeleton}
            />
            <skinnedMesh
              name="Full_body008"
              geometry={nodes.Full_body008.geometry}
              material={materials['Color.008']}
              skeleton={nodes.Full_body008.skeleton}
            />
            <skinnedMesh
              name="Glasses008"
              geometry={nodes.Glasses008.geometry}
              material={materials['Color.008']}
              skeleton={nodes.Glasses008.skeleton}
            />
            <skinnedMesh
              name="Gloves008"
              geometry={nodes.Gloves008.geometry}
              material={materials['Color.008']}
              skeleton={nodes.Gloves008.skeleton}
            />
            <skinnedMesh
              name="Hairstyle008"
              geometry={nodes.Hairstyle008.geometry}
              material={materials['Color.008']}
              skeleton={nodes.Hairstyle008.skeleton}
            />
            <skinnedMesh
              name="Hat008"
              geometry={nodes.Hat008.geometry}
              material={materials['Color.008']}
              skeleton={nodes.Hat008.skeleton}
            />
            <skinnedMesh
              name="Mustache008"
              geometry={nodes.Mustache008.geometry}
              material={materials['Color.008']}
              skeleton={nodes.Mustache008.skeleton}
            />
            <skinnedMesh
              name="Outerwear008"
              geometry={nodes.Outerwear008.geometry}
              material={materials['Color.008']}
              skeleton={nodes.Outerwear008.skeleton}
            />
            <skinnedMesh
              name="Pants008"
              geometry={nodes.Pants008.geometry}
              material={materials['Color.008']}
              skeleton={nodes.Pants008.skeleton}
            />
            <skinnedMesh
              name="Shoes008"
              geometry={nodes.Shoes008.geometry}
              material={materials['Color.008']}
              skeleton={nodes.Shoes008.skeleton}
            />
            <skinnedMesh
              name="T_Shirt008"
              geometry={nodes.T_Shirt008.geometry}
              material={materials['Color.008']}
              skeleton={nodes.T_Shirt008.skeleton}
            />
            <primitive object={nodes.Root_7} />
          </group>
        </group>
        <group name="C10_Idle" position={[2.584, 0, -0.293]}>
          <group name="Skeleton009" position={[-0.467, 0, 0.303]}>
            <skinnedMesh
              name="Accessories009"
              geometry={nodes.Accessories009.geometry}
              material={materials['Color.009']}
              skeleton={nodes.Accessories009.skeleton}
            />
            <skinnedMesh
              name="Body009"
              geometry={nodes.Body009.geometry}
              material={materials['Color.009']}
              skeleton={nodes.Body009.skeleton}
            />
            <skinnedMesh
              name="Faces009"
              geometry={nodes.Faces009.geometry}
              material={materials['Color.009']}
              skeleton={nodes.Faces009.skeleton}
            />
            <skinnedMesh
              name="Full_body009"
              geometry={nodes.Full_body009.geometry}
              material={materials['Color.009']}
              skeleton={nodes.Full_body009.skeleton}
            />
            <skinnedMesh
              name="Glasses009"
              geometry={nodes.Glasses009.geometry}
              material={materials['Color.009']}
              skeleton={nodes.Glasses009.skeleton}
            />
            <skinnedMesh
              name="Gloves009"
              geometry={nodes.Gloves009.geometry}
              material={materials['Color.009']}
              skeleton={nodes.Gloves009.skeleton}
            />
            <skinnedMesh
              name="Hairstyle009"
              geometry={nodes.Hairstyle009.geometry}
              material={materials['Color.009']}
              skeleton={nodes.Hairstyle009.skeleton}
            />
            <skinnedMesh
              name="Hat009"
              geometry={nodes.Hat009.geometry}
              material={materials['Color.009']}
              skeleton={nodes.Hat009.skeleton}
            />
            <skinnedMesh
              name="Mustache009"
              geometry={nodes.Mustache009.geometry}
              material={materials['Color.009']}
              skeleton={nodes.Mustache009.skeleton}
            />
            <skinnedMesh
              name="Outerwear009"
              geometry={nodes.Outerwear009.geometry}
              material={materials['Color.009']}
              skeleton={nodes.Outerwear009.skeleton}
            />
            <skinnedMesh
              name="Pants009"
              geometry={nodes.Pants009.geometry}
              material={materials['Color.009']}
              skeleton={nodes.Pants009.skeleton}
            />
            <skinnedMesh
              name="Shoes009"
              geometry={nodes.Shoes009.geometry}
              material={materials['Color.009']}
              skeleton={nodes.Shoes009.skeleton}
            />
            <skinnedMesh
              name="T_Shirt009"
              geometry={nodes.T_Shirt009.geometry}
              material={materials['Color.009']}
              skeleton={nodes.T_Shirt009.skeleton}
            />
            <primitive object={nodes.Root_8} />
          </group>
        </group>
        <group name="C6_Idle" position={[0.782, 0.27, 0]}>
          <group name="Skeleton005">
            <skinnedMesh
              name="Accessories005"
              geometry={nodes.Accessories005.geometry}
              material={materials['Color.011']}
              skeleton={nodes.Accessories005.skeleton}
            />
            <skinnedMesh
              name="Body005"
              geometry={nodes.Body005.geometry}
              material={materials['Color.011']}
              skeleton={nodes.Body005.skeleton}
            />
            <skinnedMesh
              name="Faces005"
              geometry={nodes.Faces005.geometry}
              material={materials['Color.011']}
              skeleton={nodes.Faces005.skeleton}
            />
            <skinnedMesh
              name="Full_body005"
              geometry={nodes.Full_body005.geometry}
              material={materials['Color.011']}
              skeleton={nodes.Full_body005.skeleton}
            />
            <skinnedMesh
              name="Glasses005"
              geometry={nodes.Glasses005.geometry}
              material={materials['Color.011']}
              skeleton={nodes.Glasses005.skeleton}
            />
            <skinnedMesh
              name="Gloves005"
              geometry={nodes.Gloves005.geometry}
              material={materials['Color.011']}
              skeleton={nodes.Gloves005.skeleton}
            />
            <skinnedMesh
              name="Hairstyle005"
              geometry={nodes.Hairstyle005.geometry}
              material={materials['Color.011']}
              skeleton={nodes.Hairstyle005.skeleton}
            />
            <skinnedMesh
              name="Hat005"
              geometry={nodes.Hat005.geometry}
              material={materials['Color.011']}
              skeleton={nodes.Hat005.skeleton}
            />
            <skinnedMesh
              name="Mustache005"
              geometry={nodes.Mustache005.geometry}
              material={materials['Color.011']}
              skeleton={nodes.Mustache005.skeleton}
            />
            <skinnedMesh
              name="Outerwear005"
              geometry={nodes.Outerwear005.geometry}
              material={materials['Color.011']}
              skeleton={nodes.Outerwear005.skeleton}
            />
            <skinnedMesh
              name="Pants005"
              geometry={nodes.Pants005.geometry}
              material={materials['Color.011']}
              skeleton={nodes.Pants005.skeleton}
            />
            <skinnedMesh
              name="Shoes005"
              geometry={nodes.Shoes005.geometry}
              material={materials['Color.011']}
              skeleton={nodes.Shoes005.skeleton}
            />
            <skinnedMesh
              name="T_Shirt005"
              geometry={nodes.T_Shirt005.geometry}
              material={materials['Color.011']}
              skeleton={nodes.T_Shirt005.skeleton}
            />
            <primitive object={nodes.Root_9} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/LiveHouse/Audience.glb')